export type League = {
  id: string;
  name: string;
  country: string;
  countryFlag: string;
  logo: string;
  season: string;
  totalMatches: number;
  matchesToday: number;
  apiEndpoints: {
    whoscored: string;
    footystats: string;
    packball: string;
  };
};

export const AVAILABLE_LEAGUES: League[] = [
  {
    id: "premier-league",
    name: "Premier League",
    country: "Inglaterra",
    countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    logo: "/logos/premier-league.png",
    season: "2024/25",
    totalMatches: 380,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/252/tournaments/2",
      footystats: "/england/premier-league",
      packball: "/matches?league=premier-league",
    },
  },
  {
    id: "championship",
    name: "Championship",
    country: "Inglaterra",
    countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    logo: "/logos/championship.png",
    season: "2024/25",
    totalMatches: 552,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/252/tournaments/7",
      footystats: "/england/championship",
      packball: "/matches?league=championship",
    },
  },
  {
    id: "primera-division",
    name: "Primera Division",
    country: "Argentina",
    countryFlag: "🇦🇷",
    logo: "/logos/primera-division.png",
    season: "2024",
    totalMatches: 378,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/11/tournaments/68",
      footystats: "/argentina/primera-division",
      packball: "/matches?league=primera-division",
    },
  },
  {
    id: "a-league",
    name: "A-League",
    country: "Austrália",
    countryFlag: "🇦🇺",
    logo: "/logos/a-league.png",
    season: "2024/25",
    totalMatches: 162,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/15/tournaments/233",
      footystats: "/australia/a-league",
      packball: "/matches?league=a-league",
    },
  },
  {
    id: "austria-bundesliga",
    name: "Bundesliga",
    country: "Áustria",
    countryFlag: "🇦🇹",
    logo: "/logos/austria-bundesliga.png",
    season: "2024/25",
    totalMatches: 132,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/17/tournaments/36",
      footystats: "/austria/bundesliga",
      packball: "/matches?league=austria-bundesliga",
    },
  },
  {
    id: "pro-league",
    name: "Pro League",
    country: "Bélgica",
    countryFlag: "🇧🇪",
    logo: "/logos/pro-league.png",
    season: "2024/25",
    totalMatches: 240,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/22/tournaments/23",
      footystats: "/belgium/pro-league",
      packball: "/matches?league=pro-league",
    },
  },
  {
    id: "brazil-serie-a",
    name: "Série A",
    country: "Brasil",
    countryFlag: "🇧🇷",
    logo: "/logos/brasileirao.png",
    season: "2024",
    totalMatches: 380,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/31/tournaments/95",
      footystats: "/brazil/campeonato-brasileiro-serie-a",
      packball: "/matches?league=brasileirao",
    },
  },
  {
    id: "brazil-serie-b",
    name: "Série B",
    country: "Brasil",
    countryFlag: "🇧🇷",
    logo: "/logos/brasileirao-b.png",
    season: "2024",
    totalMatches: 380,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/31/tournaments/96",
      footystats: "/brazil/campeonato-brasileiro-serie-b",
      packball: "/matches?league=brasileirao-b",
    },
  },
  {
    id: "denmark-superliga",
    name: "Superliga",
    country: "Dinamarca",
    countryFlag: "🇩🇰",
    logo: "/logos/superliga.png",
    season: "2024/25",
    totalMatches: 132,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/63/tournaments/118",
      footystats: "/denmark/superliga",
      packball: "/matches?league=superliga",
    },
  },
  {
    id: "france-ligue-1",
    name: "Ligue 1",
    country: "França",
    countryFlag: "🇫🇷",
    logo: "/logos/ligue-1.png",
    season: "2024/25",
    totalMatches: 306,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/74/tournaments/22",
      footystats: "/france/ligue-1",
      packball: "/matches?league=ligue-1",
    },
  },
  {
    id: "france-ligue-2",
    name: "Ligue 2",
    country: "França",
    countryFlag: "🇫🇷",
    logo: "/logos/ligue-2.png",
    season: "2024/25",
    totalMatches: 306,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/74/tournaments/23",
      footystats: "/france/ligue-2",
      packball: "/matches?league=ligue-2",
    },
  },
  {
    id: "germany-bundesliga",
    name: "Bundesliga",
    country: "Alemanha",
    countryFlag: "🇩🇪",
    logo: "/logos/bundesliga.png",
    season: "2024/25",
    totalMatches: 306,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/81/tournaments/3",
      footystats: "/germany/bundesliga",
      packball: "/matches?league=bundesliga",
    },
  },
  {
    id: "germany-2-bundesliga",
    name: "2. Bundesliga",
    country: "Alemanha",
    countryFlag: "🇩🇪",
    logo: "/logos/2-bundesliga.png",
    season: "2024/25",
    totalMatches: 306,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/81/tournaments/4",
      footystats: "/germany/2-bundesliga",
      packball: "/matches?league=2-bundesliga",
    },
  },
  {
    id: "italy-serie-a",
    name: "Serie A",
    country: "Itália",
    countryFlag: "🇮🇹",
    logo: "/logos/serie-a.png",
    season: "2024/25",
    totalMatches: 380,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/108/tournaments/5",
      footystats: "/italy/serie-a",
      packball: "/matches?league=serie-a",
    },
  },
  {
    id: "italy-serie-b",
    name: "Serie B",
    country: "Itália",
    countryFlag: "🇮🇹",
    logo: "/logos/serie-b.png",
    season: "2024/25",
    totalMatches: 380,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/108/tournaments/6",
      footystats: "/italy/serie-b",
      packball: "/matches?league=serie-b",
    },
  },
  {
    id: "netherlands-eredivisie",
    name: "Eredivisie",
    country: "Holanda",
    countryFlag: "🇳🇱",
    logo: "/logos/eredivisie.png",
    season: "2024/25",
    totalMatches: 306,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/155/tournaments/13",
      footystats: "/netherlands/eredivisie",
      packball: "/matches?league=eredivisie",
    },
  },
  {
    id: "portugal-liga-nos",
    name: "Liga NOS",
    country: "Portugal",
    countryFlag: "🇵🇹",
    logo: "/logos/liga-nos.png",
    season: "2024/25",
    totalMatches: 306,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/177/tournaments/155",
      footystats: "/portugal/liga-nos",
      packball: "/matches?league=liga-nos",
    },
  },
  {
    id: "saudi-professional-league",
    name: "Professional League",
    country: "Arábia Saudita",
    countryFlag: "🇸🇦",
    logo: "/logos/saudi-pro-league.png",
    season: "2024/25",
    totalMatches: 306,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/191/tournaments/220",
      footystats: "/saudi-arabia/professional-league",
      packball: "/matches?league=saudi-pro-league",
    },
  },
  {
    id: "scotland-premiership",
    name: "Premiership",
    country: "Escócia",
    countryFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    logo: "/logos/premiership.png",
    season: "2024/25",
    totalMatches: 228,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/253/tournaments/12",
      footystats: "/scotland/premiership",
      packball: "/matches?league=scotland-premiership",
    },
  },
  {
    id: "spain-la-liga",
    name: "La Liga",
    country: "Espanha",
    countryFlag: "🇪🇸",
    logo: "/logos/laliga.png",
    season: "2024/25",
    totalMatches: 380,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/206/tournaments/4",
      footystats: "/spain/la-liga",
      packball: "/matches?league=la-liga",
    },
  },
  {
    id: "switzerland-super-league",
    name: "Super League",
    country: "Suíça",
    countryFlag: "🇨🇭",
    logo: "/logos/switzerland-super-league.png",
    season: "2024/25",
    totalMatches: 132,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/213/tournaments/34",
      footystats: "/switzerland/super-league",
      packball: "/matches?league=switzerland-super-league",
    },
  },
  {
    id: "turkey-super-lig",
    name: "Süper Lig",
    country: "Turquia",
    countryFlag: "🇹🇷",
    logo: "/logos/super-lig.png",
    season: "2024/25",
    totalMatches: 342,
    matchesToday: 0,
    apiEndpoints: {
      whoscored: "/regions/221/tournaments/11",
      footystats: "/turkey/super-lig",
      packball: "/matches?league=super-lig",
    },
  },
];
